### ISSUE TITLE
Update for Laravel ^11.0 and php ^8.0

### ISSUE THREAD

**Issue by virenderscideas** [riteshjha/laravel-permission#1]
Hi @riteshjha ,

Seems this package is not updated with latest Laravel, php.

I am using php version (8.2.8)
&
"laravel/framework": "^11.0",

![image](https://github.com/riteshjha/laravel-permission/assets/65526033/af6600ca-c6bd-4e43-b3da-1dceb4839c6e)

**Comment by riteshjha** [comment]
added support in version [2.0.2](https://github.com/riteshjha/laravel-permission/releases/tag/v2.0.2). Check it and if you find any bug report.
